# Generated by Django 2.0.10 on 2019-02-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudinter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='university_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='university_start',
            field=models.DateField(null=True),
        ),
    ]
