# Generated by Django 2.0.10 on 2019-02-09 21:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cloudinter', '0002_auto_20190208_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
