# Generated by Django 2.0.10 on 2019-02-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudinter', '0004_auto_20190219_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='phonenumber',
            field=models.TextField(null=True),
        ),
    ]
